name: my_project_modame
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgroundimage.jpg
    - assets/logo.png
    - assets/welcome_pic.jpg
    - assets/google_logo.png
    - assets/register_pic.jpg

    - assets/Homepic.jpg
    - assets/She&He.png
    - assets/Hourglass.png
    - assets/HourglassR.png
    - assets/Rounded.png
    - assets/Rectangle.png
    - assets/Triangle.png
    - assets/Inverted_triangle.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png
    - assets/9.png
    - assets/10.png
    - assets/11.png
    - assets/12.png
